### ISSUE TITLE
gvm use could return what is used currently

### ISSUE THREAD

**Issue by joeblew99** [andrewkroh/gvm#19]
when you have lots of golang versions installed, it would be useful to be abl to find the current one being used.

So was thinking that ''' gvm list ''' could do what it does now but highlight which one is currently used.

The reason is because i am trying to automate the use of gvm for testing and CI.

Sorry about so many issues !! Hope i am not over issuing ?

**Comment by andrewkroh** [comment]
This could be a nice to have feature.

But how is this useful for automation? Running `go version` would be more reliable means of checking the current version in the `PATH`.

**Comment by joeblew99** [comment]
point taken :) thanks
