### ISSUE TITLE
Build artifact for macOS m1 architecture

### ISSUE THREAD

**Issue by ph** [andrewkroh/gvm#36]
Release artifact for macOS m1 architecture.

**Comment by andrewkroh** [comment]
An M1 binary is now available as a pre-release. I'll make a production release after Go 1.16 is available.

See https://github.com/andrewkroh/gvm/releases/tag/v0.3.1-rc1

**Comment by ph** [comment]
tested with the rc1, `gvm 1.16beta1` works as expected. Thanks
