### ISSUE TITLE
Unable to install Go 1.21.0 with gvm

### ISSUE THREAD

**Issue by mikemadden42** [andrewkroh/gvm#64]
Go 1.21.0 was [released](https://go.dev/blog/go1.21) earlier this week.

I'm having issues installing it with gvm.

```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.8
BuildVersion:	21G725
```

```
$ gvm --version
v0.5.0
```

```
$ eval $(gvm 1.21.0)
gvm: error: unknown version 1.21
```

I'm having a similar issue on Ubuntu 22.04.3.

**Comment by andrewkroh** [comment]
Please upgrade to [v0.5.1](https://github.com/andrewkroh/gvm/releases/tag/v0.5.1).

**Comment by andrewkroh** [comment]
Duplicates #61.
