### ISSUE TITLE
Why does VirusTotal say that some vendors flag the .exe as Trojan.Malware?

### ISSUE THREAD

**Issue by Robinzon100** [andrewkroh/gvm#87]
![image](https://github.com/andrewkroh/gvm/assets/27893373/ee091c46-5510-4e8f-922d-8bfdf9ca8d62)

**Comment by andrewkroh** [comment]
False positives are a pretty common occurrence for Go programs. See https://go.dev/doc/faq#virus. 

You should be able to reproduce the same false positives if you build from source, and retest your binaries. The binaries attached to releases are fully produced within Github Action runners via automation and the toolchain should be entirely reproducible if you review the GH action config and go.mod.

Here's a scan of gvm-windows-amd64.exe from [v0.5.2](https://github.com/andrewkroh/gvm/releases/tag/v0.5.2): https://www.virustotal.com/gui/file/27ef4c679475e480346fcfd4e3d8acc254f476491eeb6c572897e8960b5ed8dc

**Comment by andrewkroh** [comment]
NVM had a similar issue with Crowdstrike Falcon. https://github.com/coreybutler/nvm-windows/issues/769

**Comment by Robinzon100** [comment]
My apologies Andrew I should have researched this more, instead of creating an issue

**Comment by Robinzon100** [comment]
My apologies Andrew @andrewkroh I should have researched this more, instead of creating an issue
