### ISSUE TITLE
v1.0.22  big lag 0,420ms

### ISSUE THREAD

**Issue by batot1** [andrewkroh/gvm#89]
it@ai:~$ gvm version
Go Version Manager v1.0.22 installed at /home/it/.gvm

t@ai:~$ time cd python/

real	0m0.426s
user	0m0.322s
sys	0m0.178s
it@ai:~/python$ time cd git
-bash: cd: git: No such file or directory

real	0m0.430s
user	0m0.327s
sys	0m0.176s
it@ai:~/python$ time cd lib

real	0m0.435s
user	0m0.339s
sys	0m0.172s
it@ai:~/python/lib$ 

Past remove script from .bashrc have
it@ai:~$ time cd python/

real	0m0.000s
user	0m0.000s
sys	0m0.000s
it@ai:~/python$ time cd lib

real	0m0.000s
user	0m0.000s
sys	0m0.000s
it@ai:~/python/lib$ 

Sorry this lag isn't acceptable for me and I was switched off this broken package.
In MC I must waiting too long time for change screen. Tragic comedy.

**Comment by andrewkroh** [comment]
You are not using this project. Tragic comedy.

As of today, the latest release is [v0.5.2](https://github.com/andrewkroh/gvm/releases/tag/v0.5.2). This project only accepts `gvm --version` and not `gvm version`. 

> $ gvm --version
> v0.5.2
